version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    commit-message:
      include: "scope"
      prefix: "chore"
    directory: "/"
    schedule:
      interval: "daily"
